---

- name: Add the system users (department pattern)
  user:
    name: "{{item.value.username}}"
    state: "{{item.value.state|default('present')}}"
    system: "{{item.value.system|default(false)}}"
    comment: "{{item.key}}"
  with_dict: autologic_users
  when: item.value.department in autologic_departments

- name: Configure user UIDs (department pattern)
  user:
    name: "{{item.value.username}}"
    uid: "{{item.value.uid}}"
  with_dict: autologic_users
  when: item.value.uid is defined and item.value.department in autologic_departments

- name: Configure user home directory (department pattern)
  user:
    name: "{{item.value.username}}"
    home: "{{item.value.home}}"
  with_dict: autologic_users
  when: item.value.home is defined and item.value.department in autologic_departments

- name: Configure user groups (department pattern)
  user:
    name: "{{item.value.username}}"
    groups: "{{item.value.groups|join(',')}}"
  with_dict: autologic_users
  when: item.value.groups is defined and item.value.department in autologic_departments

- name: Add user SSH (public) keys
  authorized_key:
    user: "{{item.0.username}}"
    key: "{{item.1}}"
    state: 'present'
  with_subelements:
    - autologic_users
    - sshkeys
  when: item.value.department in autologic_departments and autologic_manage_sshkeys
